parent: "lablabs/terraform-aws-eks-universal-addon"   # Parent repo, against this we compare sub repos
repos:
  - name: "lablabs/terraform-aws-eks-argo-workflows" 
    category: 
    - "addon-irsa"
  - name: "lablabs/terraform-aws-eks-external-secrets" 
    category: []
  - name: "lablabs/terraform-aws-eks-external-dns" 
    category: 
    - "addon-irsa"
  - name: "lablabs/terraform-aws-eks-ebs-csi-driver" 
    category: 
    - "addon-irsa"
  - name: "lablabs/terraform-aws-eks-cilium"
    category: []
  - name: "lablabs/terraform-aws-eks-kube-state-metrics"
    category: []
  - name: "lablabs/terraform-aws-eks-kyverno"
    category:
    - "addon-irsa"
  - name: "lablabs/terraform-aws-eks-kyverno-policy-reporter"
    category:
    - "addon-irsa"
  - name: "lablabs/terraform-aws-eks-metrics-server"
    category: []
  - name: "lablabs/terraform-aws-eks-node-problem-detector"
    category: []
  - name: "lablabs/terraform-aws-eks-cert-manager"
    category: 
    - "addon-irsa"
